apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice4-doctor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice4-doctor-service
  template:
    metadata:
      labels:
        app: microservice4-doctor-service
    spec:
      containers:
        - name: microservice4-doctor-service
          image: microservice4-doctor-service:local
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: microservice4-doctor-service
spec:
  selector:
    app: microservice4-doctor-service
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort
